Internal Server Error: /api/users/send-email/
Traceback (most recent call last):
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\email_outreach\users\views.py", line 211, in post
    validate_email(email)  # Validate the email format
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\email_validator\validate_email.py", line 171, in validate_email
    from .deliverability import validate_email_deliverability
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\email_validator\deliverability.py", line 7, in <module>
    import dns.resolver
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\__init__.py", line 27, in <module>
    from .Base import DnsRequest
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\Base.py", line 44, in <module>
    from . import Lib
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\Lib.py", line 35, in <module>
    import DNS
ModuleNotFoundError: No module named 'DNS'
"POST /api/users/send-email/ HTTP/1.1" 500 162527
Internal Server Error: /api/users/send-email/
Traceback (most recent call last):
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\email_outreach\users\views.py", line 211, in post
    validate_email(email)  # Validate the email format
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\email_validator\validate_email.py", line 171, in validate_email
    from .deliverability import validate_email_deliverability
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\email_validator\deliverability.py", line 7, in <module>
    import dns.resolver
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\__init__.py", line 27, in <module>
    from .Base import DnsRequest
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\Base.py", line 44, in <module>
    from . import Lib
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\Lib.py", line 35, in <module>
    import DNS
ModuleNotFoundError: No module named 'DNS'
"POST /api/users/send-email/ HTTP/1.1" 500 162527
Internal Server Error: /api/users/send-email/
Traceback (most recent call last):
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\email_outreach\users\views.py", line 211, in post
    validate_email(email)  # Validate the email format
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\email_validator\validate_email.py", line 171, in validate_email
    from .deliverability import validate_email_deliverability
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\email_validator\deliverability.py", line 7, in <module>
    import dns.resolver
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\__init__.py", line 27, in <module>
    from .Base import DnsRequest
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\Base.py", line 44, in <module>
    from . import Lib
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\Lib.py", line 35, in <module>
    import DNS
ModuleNotFoundError: No module named 'DNS'
"POST /api/users/send-email/ HTTP/1.1" 500 162527
Internal Server Error: /api/users/send-email/
Traceback (most recent call last):
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\email_outreach\users\views.py", line 210, in post
    validate_email(email)  # Validate the email format
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\email_validator\validate_email.py", line 171, in validate_email
    from .deliverability import validate_email_deliverability
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\email_validator\deliverability.py", line 7, in <module>
    import dns.resolver
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\__init__.py", line 27, in <module>
    from .Base import DnsRequest
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\Base.py", line 44, in <module>
    from . import Lib
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\Lib.py", line 35, in <module>
    import DNS
ModuleNotFoundError: No module named 'DNS'
"POST /api/users/send-email/ HTTP/1.1" 500 162525
Internal Server Error: /api/users/send-email/
Traceback (most recent call last):
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\email_outreach\users\views.py", line 214, in post
    validate_email(email)  # Validate the email format
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\email_validator\validate_email.py", line 171, in validate_email
    from .deliverability import validate_email_deliverability
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\email_validator\deliverability.py", line 7, in <module>
    import dns.resolver
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\__init__.py", line 27, in <module>
    from .Base import DnsRequest
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\Base.py", line 44, in <module>
    from . import Lib
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\Lib.py", line 35, in <module>
    import DNS
ModuleNotFoundError: No module named 'DNS'
"POST /api/users/send-email/ HTTP/1.1" 500 162568
Internal Server Error: /api/users/send-email/
Traceback (most recent call last):
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\email_outreach\users\views.py", line 214, in post
    validate_email(email)  # Validate the email format
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\email_validator\validate_email.py", line 171, in validate_email
    from .deliverability import validate_email_deliverability
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\email_validator\deliverability.py", line 7, in <module>
    import dns.resolver
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\__init__.py", line 27, in <module>
    from .Base import DnsRequest
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\Base.py", line 44, in <module>
    from . import Lib
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\Lib.py", line 35, in <module>
    import DNS
ModuleNotFoundError: No module named 'DNS'
"POST /api/users/send-email/ HTTP/1.1" 500 162568
Internal Server Error: /api/users/send-email-multiple/
Traceback (most recent call last):
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\email_outreach\users\views.py", line 214, in post
    validate_email(email)  # Validate the email format
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\email_validator\validate_email.py", line 171, in validate_email
    from .deliverability import validate_email_deliverability
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\email_validator\deliverability.py", line 7, in <module>
    import dns.resolver
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\__init__.py", line 27, in <module>
    from .Base import DnsRequest
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\Base.py", line 44, in <module>
    from . import Lib
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\Lib.py", line 35, in <module>
    import DNS
ModuleNotFoundError: No module named 'DNS'
"POST /api/users/send-email-multiple/ HTTP/1.1" 500 162712
Internal Server Error: /api/users/send-email-multiple/
Traceback (most recent call last):
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\email_outreach\users\views.py", line 214, in post
    validate_email(email)  # Validate the email format
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\email_validator\validate_email.py", line 171, in validate_email
    from .deliverability import validate_email_deliverability
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\email_validator\deliverability.py", line 7, in <module>
    import dns.resolver
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\__init__.py", line 27, in <module>
    from .Base import DnsRequest
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\Base.py", line 44, in <module>
    from . import Lib
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\Lib.py", line 35, in <module>
    import DNS
ModuleNotFoundError: No module named 'DNS'
"POST /api/users/send-email-multiple/ HTTP/1.1" 500 162699
Internal Server Error: /api/users/send-email-multiple/
Traceback (most recent call last):
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\email_outreach\users\views.py", line 216, in post
    validate_email(email)  # Validate the email format
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\email_validator\validate_email.py", line 171, in validate_email
    from .deliverability import validate_email_deliverability
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\email_validator\deliverability.py", line 7, in <module>
    import dns.resolver
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\__init__.py", line 27, in <module>
    from .Base import DnsRequest
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\Base.py", line 44, in <module>
    from . import Lib
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\Lib.py", line 35, in <module>
    import DNS
ModuleNotFoundError: No module named 'DNS'
"POST /api/users/send-email-multiple/ HTTP/1.1" 500 162657
Internal Server Error: /api/users/send-email/
Traceback (most recent call last):
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\email_outreach\users\views.py", line 217, in post
    validate_email(email)  # Validate the email format
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\email_validator\validate_email.py", line 171, in validate_email
    from .deliverability import validate_email_deliverability
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\email_validator\deliverability.py", line 7, in <module>
    import dns.resolver
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\__init__.py", line 27, in <module>
    from .Base import DnsRequest
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\Base.py", line 44, in <module>
    from . import Lib
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\Lib.py", line 35, in <module>
    import DNS
ModuleNotFoundError: No module named 'DNS'
"POST /api/users/send-email/ HTTP/1.1" 500 162513
Internal Server Error: /admin/users/emailtrack/
Traceback (most recent call last):
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\db\models\options.py", line 676, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'action_checkbox'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\contrib\admin\utils.py", line 290, in lookup_field
    f = _get_non_gfk_field(opts, name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\contrib\admin\utils.py", line 330, in _get_non_gfk_field
    field = opts.get_field(name)
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\db\models\options.py", line 678, in get_field
    raise FieldDoesNotExist(
django.core.exceptions.FieldDoesNotExist: EmailTrack has no field named 'action_checkbox'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\contrib\admin\templatetags\base.py", line 45, in render
    return super().render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 346, in result_list
    "results": list(results(cl)),
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 322, in results
    yield ResultList(None, items_for_result(cl, res, None))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 313, in __init__
    super().__init__(*items)
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 218, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\contrib\admin\utils.py", line 299, in lookup_field
    value = attr(obj)
            ^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\contrib\admin\options.py", line 1030, in action_checkbox
    _("Select this object for an action - {}"), str(obj)
                                                ^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\email_outreach\users\models.py", line 55, in __str__
    return f"Email to {self.recipient} by {self.username} at {self.email_sent_date}"
                                                              ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'EmailTrack' object has no attribute 'email_sent_date'. Did you mean: 'emailsentdate'?
"GET /admin/users/emailtrack/ HTTP/1.1" 500 364157
Internal Server Error: /admin/users/emailtrack/
Traceback (most recent call last):
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\db\models\options.py", line 676, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'action_checkbox'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\contrib\admin\utils.py", line 290, in lookup_field
    f = _get_non_gfk_field(opts, name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\contrib\admin\utils.py", line 330, in _get_non_gfk_field
    field = opts.get_field(name)
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\db\models\options.py", line 678, in get_field
    raise FieldDoesNotExist(
django.core.exceptions.FieldDoesNotExist: EmailTrack has no field named 'action_checkbox'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\contrib\admin\templatetags\base.py", line 45, in render
    return super().render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 346, in result_list
    "results": list(results(cl)),
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 322, in results
    yield ResultList(None, items_for_result(cl, res, None))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 313, in __init__
    super().__init__(*items)
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 218, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\contrib\admin\utils.py", line 299, in lookup_field
    value = attr(obj)
            ^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\contrib\admin\options.py", line 1030, in action_checkbox
    _("Select this object for an action - {}"), str(obj)
                                                ^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\email_outreach\users\models.py", line 55, in __str__
    return f"Email to {self.recipient} by {self.username} at {self.email_sent_date}"
                                                              ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'EmailTrack' object has no attribute 'email_sent_date'. Did you mean: 'emailsentdate'?
"GET /admin/users/emailtrack/ HTTP/1.1" 500 364157
Internal Server Error: /admin/users/emailtrack/
Traceback (most recent call last):
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\db\models\options.py", line 676, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'action_checkbox'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\contrib\admin\utils.py", line 290, in lookup_field
    f = _get_non_gfk_field(opts, name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\contrib\admin\utils.py", line 330, in _get_non_gfk_field
    field = opts.get_field(name)
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\db\models\options.py", line 678, in get_field
    raise FieldDoesNotExist(
django.core.exceptions.FieldDoesNotExist: EmailTrack has no field named 'action_checkbox'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\contrib\admin\templatetags\base.py", line 45, in render
    return super().render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\template\library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 346, in result_list
    "results": list(results(cl)),
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 322, in results
    yield ResultList(None, items_for_result(cl, res, None))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 313, in __init__
    super().__init__(*items)
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 218, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\contrib\admin\utils.py", line 299, in lookup_field
    value = attr(obj)
            ^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\contrib\admin\options.py", line 1030, in action_checkbox
    _("Select this object for an action - {}"), str(obj)
                                                ^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\email_outreach\users\models.py", line 55, in __str__
    return f"Email to {self.recipient} by {self.username} at {self.email_sent_date}"
                                                              ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'EmailTrack' object has no attribute 'email_sent_date'. Did you mean: 'emailsentdate'?
"GET /admin/users/emailtrack/ HTTP/1.1" 500 364157
