Internal Server Error: /api/users/send-email/
Traceback (most recent call last):
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\email_outreach\users\views.py", line 211, in post
    validate_email(email)  # Validate the email format
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\email_validator\validate_email.py", line 171, in validate_email
    from .deliverability import validate_email_deliverability
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\email_validator\deliverability.py", line 7, in <module>
    import dns.resolver
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\__init__.py", line 27, in <module>
    from .Base import DnsRequest
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\Base.py", line 44, in <module>
    from . import Lib
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\Lib.py", line 35, in <module>
    import DNS
ModuleNotFoundError: No module named 'DNS'
"POST /api/users/send-email/ HTTP/1.1" 500 162527
Internal Server Error: /api/users/send-email/
Traceback (most recent call last):
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\email_outreach\users\views.py", line 211, in post
    validate_email(email)  # Validate the email format
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\email_validator\validate_email.py", line 171, in validate_email
    from .deliverability import validate_email_deliverability
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\email_validator\deliverability.py", line 7, in <module>
    import dns.resolver
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\__init__.py", line 27, in <module>
    from .Base import DnsRequest
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\Base.py", line 44, in <module>
    from . import Lib
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\Lib.py", line 35, in <module>
    import DNS
ModuleNotFoundError: No module named 'DNS'
"POST /api/users/send-email/ HTTP/1.1" 500 162527
Internal Server Error: /api/users/send-email/
Traceback (most recent call last):
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\email_outreach\users\views.py", line 211, in post
    validate_email(email)  # Validate the email format
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\email_validator\validate_email.py", line 171, in validate_email
    from .deliverability import validate_email_deliverability
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\email_validator\deliverability.py", line 7, in <module>
    import dns.resolver
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\__init__.py", line 27, in <module>
    from .Base import DnsRequest
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\Base.py", line 44, in <module>
    from . import Lib
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\Lib.py", line 35, in <module>
    import DNS
ModuleNotFoundError: No module named 'DNS'
"POST /api/users/send-email/ HTTP/1.1" 500 162527
Internal Server Error: /api/users/send-email/
Traceback (most recent call last):
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\email_outreach\users\views.py", line 210, in post
    validate_email(email)  # Validate the email format
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\email_validator\validate_email.py", line 171, in validate_email
    from .deliverability import validate_email_deliverability
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\email_validator\deliverability.py", line 7, in <module>
    import dns.resolver
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\__init__.py", line 27, in <module>
    from .Base import DnsRequest
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\Base.py", line 44, in <module>
    from . import Lib
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\Lib.py", line 35, in <module>
    import DNS
ModuleNotFoundError: No module named 'DNS'
"POST /api/users/send-email/ HTTP/1.1" 500 162525
Internal Server Error: /api/users/send-email/
Traceback (most recent call last):
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\email_outreach\users\views.py", line 214, in post
    validate_email(email)  # Validate the email format
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\email_validator\validate_email.py", line 171, in validate_email
    from .deliverability import validate_email_deliverability
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\email_validator\deliverability.py", line 7, in <module>
    import dns.resolver
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\__init__.py", line 27, in <module>
    from .Base import DnsRequest
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\Base.py", line 44, in <module>
    from . import Lib
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\Lib.py", line 35, in <module>
    import DNS
ModuleNotFoundError: No module named 'DNS'
"POST /api/users/send-email/ HTTP/1.1" 500 162568
Internal Server Error: /api/users/send-email/
Traceback (most recent call last):
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\email_outreach\users\views.py", line 214, in post
    validate_email(email)  # Validate the email format
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\email_validator\validate_email.py", line 171, in validate_email
    from .deliverability import validate_email_deliverability
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\email_validator\deliverability.py", line 7, in <module>
    import dns.resolver
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\__init__.py", line 27, in <module>
    from .Base import DnsRequest
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\Base.py", line 44, in <module>
    from . import Lib
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\Lib.py", line 35, in <module>
    import DNS
ModuleNotFoundError: No module named 'DNS'
"POST /api/users/send-email/ HTTP/1.1" 500 162568
Internal Server Error: /api/users/send-email-multiple/
Traceback (most recent call last):
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\email_outreach\users\views.py", line 214, in post
    validate_email(email)  # Validate the email format
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\email_validator\validate_email.py", line 171, in validate_email
    from .deliverability import validate_email_deliverability
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\email_validator\deliverability.py", line 7, in <module>
    import dns.resolver
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\__init__.py", line 27, in <module>
    from .Base import DnsRequest
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\Base.py", line 44, in <module>
    from . import Lib
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\Lib.py", line 35, in <module>
    import DNS
ModuleNotFoundError: No module named 'DNS'
"POST /api/users/send-email-multiple/ HTTP/1.1" 500 162712
Internal Server Error: /api/users/send-email-multiple/
Traceback (most recent call last):
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\email_outreach\users\views.py", line 214, in post
    validate_email(email)  # Validate the email format
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\email_validator\validate_email.py", line 171, in validate_email
    from .deliverability import validate_email_deliverability
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\email_validator\deliverability.py", line 7, in <module>
    import dns.resolver
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\__init__.py", line 27, in <module>
    from .Base import DnsRequest
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\Base.py", line 44, in <module>
    from . import Lib
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\Lib.py", line 35, in <module>
    import DNS
ModuleNotFoundError: No module named 'DNS'
"POST /api/users/send-email-multiple/ HTTP/1.1" 500 162699
Internal Server Error: /api/users/send-email-multiple/
Traceback (most recent call last):
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\email_outreach\users\views.py", line 216, in post
    validate_email(email)  # Validate the email format
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\email_validator\validate_email.py", line 171, in validate_email
    from .deliverability import validate_email_deliverability
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\email_validator\deliverability.py", line 7, in <module>
    import dns.resolver
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\__init__.py", line 27, in <module>
    from .Base import DnsRequest
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\Base.py", line 44, in <module>
    from . import Lib
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\Lib.py", line 35, in <module>
    import DNS
ModuleNotFoundError: No module named 'DNS'
"POST /api/users/send-email-multiple/ HTTP/1.1" 500 162657
Internal Server Error: /api/users/send-email/
Traceback (most recent call last):
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\email_outreach\users\views.py", line 217, in post
    validate_email(email)  # Validate the email format
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\email_validator\validate_email.py", line 171, in validate_email
    from .deliverability import validate_email_deliverability
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\email_validator\deliverability.py", line 7, in <module>
    import dns.resolver
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\__init__.py", line 27, in <module>
    from .Base import DnsRequest
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\Base.py", line 44, in <module>
    from . import Lib
  File "C:\Users\DArk Lord\Desktop\ShubhamSingh-Assignment\env\Lib\site-packages\dns\Lib.py", line 35, in <module>
    import DNS
ModuleNotFoundError: No module named 'DNS'
"POST /api/users/send-email/ HTTP/1.1" 500 162513
